import { ExpenseType, PaymentMethod } from '@/types';

export const mockExpenses = [
  {
    _id: 'e1',
    houseId: 'h1',
    houseAddress: '123 Main Street',
    expenseType: ExpenseType.ELECTRICITY,
    amount: 150,
    paymentMethod: PaymentMethod.TRANSFER,
    expenseDate: new Date('2023-02-15'),
    period: { month: 2, year: 2023 },
    paidBy: 'Admin',
    receiptNumber: 'EXP-001',
  },
  {
    _id: 'e2',
    houseId: 'h1',
    houseAddress: '123 Main Street',
    expenseType: ExpenseType.WATER,
    amount: 80,
    paymentMethod: PaymentMethod.TRANSFER,
    expenseDate: new Date('2023-02-20'),
    period: { month: 2, year: 2023 },
    paidBy: 'Admin',
    receiptNumber: 'EXP-002',
  },
  {
    _id: 'e3',
    houseId: 'h1',
    houseAddress: '123 Main Street',
    expenseType: ExpenseType.REPAIR,
    amount: 200,
    paymentMethod: PaymentMethod.CASH,
    expenseDate: new Date('2023-03-05'),
    paidBy: 'Admin',
    notes: 'Fixed broken window in room 201',
    receiptNumber: 'EXP-003',
  },
  {
    _id: 'e4',
    houseId: 'h2',
    houseAddress: '456 Oak Avenue',
    expenseType: ExpenseType.ELECTRICITY,
    amount: 120,
    paymentMethod: PaymentMethod.TRANSFER,
    expenseDate: new Date('2023-02-18'),
    period: { month: 2, year: 2023 },
    paidBy: 'Admin',
    receiptNumber: 'EXP-004',
  },
  {
    _id: 'e5',
    houseId: 'h2',
    houseAddress: '456 Oak Avenue',
    expenseType: ExpenseType.CLEANING,
    amount: 100,
    paymentMethod: PaymentMethod.CASH,
    expenseDate: new Date('2023-03-01'),
    paidBy: 'Admin',
    receiptNumber: 'EXP-005',
  },
];

export const houses = [
  { id: 'h1', address: '123 Main Street' },
  { id: 'h2', address: '456 Oak Avenue' },
  { id: 'h3', address: '789 Pine Road' },
  { id: 'h4', address: '101 Cedar Lane' },
];
