import { HouseStatus, type IHouse, IRoom, RoomStatus } from '@/types';

export const mockHouses: IHouse[] = [
  {
    _id: 'h1',
    address: '123 Main Street',
    totalRooms: 6,
    monthlyBaseRent: 1200,
    description: 'Two-story house with garden',
    status: HouseStatus.ACTIVE,
    createdAt: new Date('2023-01-15'),
  },
  {
    _id: 'h2',
    address: '456 Oak Avenue',
    totalRooms: 4,
    monthlyBaseRent: 950,
    description: 'Single-story house near downtown',
    status: HouseStatus.ACTIVE,
    createdAt: new Date('2023-02-20'),
  },
  {
    _id: 'h3',
    address: '789 Pine Road',
    totalRooms: 8,
    monthlyBaseRent: 1500,
    description: 'Large house with backyard',
    status: HouseStatus.MAINTENANCE,
    createdAt: new Date('2023-03-10'),
  },
  {
    _id: 'h4',
    address: '101 Cedar Lane',
    totalRooms: 5,
    monthlyBaseRent: 1100,
    description: 'Cozy house with modern amenities',
    status: HouseStatus.INACTIVE,
    createdAt: new Date('2023-04-05'),
  },
];

export const mockRooms: Record<string, IRoom[]> = {
  h1: [
    {
      _id: 'r1',
      houseId: 'h1',
      roomNumber: '101',
      monthlyRent: 300,
      status: RoomStatus.OCCUPIED,
      maxTenants: 2,
      currentTenants: ['t1'],
    },
    {
      _id: 'r2',
      houseId: 'h1',
      roomNumber: '102',
      monthlyRent: 250,
      status: RoomStatus.OCCUPIED,
      maxTenants: 1,
      currentTenants: ['t2'],
    },
    {
      _id: 'r3',
      houseId: 'h1',
      roomNumber: '103',
      monthlyRent: 350,
      status: RoomStatus.VACANT,
      maxTenants: 2,
      currentTenants: [],
    },
    {
      _id: 'r4',
      houseId: 'h1',
      roomNumber: '201',
      monthlyRent: 320,
      status: RoomStatus.OCCUPIED,
      maxTenants: 2,
      currentTenants: ['t3', 't4'],
    },
    {
      _id: 'r5',
      houseId: 'h1',
      roomNumber: '202',
      monthlyRent: 280,
      status: RoomStatus.MAINTENANCE,
      maxTenants: 1,
      currentTenants: [],
    },
    {
      _id: 'r6',
      houseId: 'h1',
      roomNumber: '203',
      monthlyRent: 300,
      status: RoomStatus.OCCUPIED,
      maxTenants: 1,
      currentTenants: ['t5'],
    },
  ],
  h2: [
    {
      _id: 'r7',
      houseId: 'h2',
      roomNumber: '101',
      monthlyRent: 250,
      status: RoomStatus.OCCUPIED,
      maxTenants: 1,
      currentTenants: ['t6'],
    },
    {
      _id: 'r8',
      houseId: 'h2',
      roomNumber: '102',
      monthlyRent: 280,
      status: RoomStatus.OCCUPIED,
      maxTenants: 1,
      currentTenants: ['t7'],
    },
    {
      _id: 'r9',
      houseId: 'h2',
      roomNumber: '201',
      monthlyRent: 300,
      status: RoomStatus.VACANT,
      maxTenants: 2,
      currentTenants: [],
    },
    {
      _id: 'r10',
      houseId: 'h2',
      roomNumber: '202',
      monthlyRent: 320,
      status: RoomStatus.OCCUPIED,
      maxTenants: 2,
      currentTenants: ['t8', 't9'],
    },
  ],
};
