import { ITenant, TenantStatus } from '@/types';

export const mockTenants: ITenant[] = [
  {
    _id: 't1',
    name: 'John Doe',
    phoneNumber: '+1234567890',
    rentStartDate: new Date('2023-01-15'),
    monthlyRent: 300,
    securityDeposit: 600,
    balance: 0,
    roomId: 'r1',
    houseId: 'h1',
    status: TenantStatus.ACTIVE,
  },
  {
    _id: 't2',
    name: 'Jane Smith',
    phoneNumber: '+1987654321',
    rentStartDate: new Date('2023-02-01'),
    monthlyRent: 250,
    securityDeposit: 500,
    balance: -150,
    roomId: 'r2',
    houseId: 'h1',
    status: TenantStatus.ACTIVE,
  },
  {
    _id: 't3',
    name: 'Mike Johnson',
    phoneNumber: '+1122334455',
    rentStartDate: new Date('2023-03-10'),
    monthlyRent: 320,
    securityDeposit: 640,
    balance: 0,
    roomId: 'r4',
    houseId: 'h1',
    status: TenantStatus.ACTIVE,
  },
  {
    _id: 't6',
    name: 'Sarah Williams',
    phoneNumber: '+1555666777',
    rentStartDate: new Date('2023-02-15'),
    rentEndDate: new Date('2023-08-15'),
    monthlyRent: 250,
    securityDeposit: 500,
    balance: 0,
    roomId: 'r7',
    houseId: 'h2',
    status: TenantStatus.FORMER,
  },
];

export const mockRoomNumbers: Record<string, string> = {
  r1: '101',
  r2: '102',
  r3: '103',
  r4: '201',
  r5: '202',
  r6: '203',
  r7: '101',
  r8: '102',
  r9: '201',
  r10: '202',
};

import { PaymentStatus, PaymentType, PaymentMethod } from '@/types';

// Separated mock payment data into a utility file
export function getMockPayments() {
  return [
    {
      _id: 'p1',
      tenantId: 't1',
      roomId: 'r1',
      houseId: 'h1',
      amount: 300,
      paymentType: PaymentType.RENT,
      paymentMethod: PaymentMethod.CASH,
      paymentDate: new Date('2023-02-01'),
      period: { month: 2, year: 2023 },
      status: PaymentStatus.PAID,
      receiptNumber: 'REC-001',
    },
    {
      _id: 'p2',
      tenantId: 't1',
      roomId: 'r1',
      houseId: 'h1',
      amount: 300,
      paymentType: PaymentType.RENT,
      paymentMethod: PaymentMethod.TRANSFER,
      paymentDate: new Date('2023-03-02'),
      period: { month: 3, year: 2023 },
      status: PaymentStatus.PAID,
      receiptNumber: 'REC-015',
    },
    {
      _id: 'p3',
      tenantId: 't1',
      roomId: 'r1',
      houseId: 'h1',
      amount: 600,
      paymentType: PaymentType.DEPOSIT,
      paymentMethod: PaymentMethod.CASH,
      paymentDate: new Date('2023-01-15'),
      status: PaymentStatus.PAID,
      receiptNumber: 'DEP-001',
    },
    {
      _id: 'p7',
      tenantId: 't1',
      roomId: 'r1',
      houseId: 'h1',
      amount: 300,
      paymentType: PaymentType.RENT,
      paymentMethod: PaymentMethod.TRANSFER,
      paymentDate: new Date('2023-04-03'),
      period: { month: 4, year: 2023 },
      status: PaymentStatus.PENDING,
      receiptNumber: 'REC-030',
    },
  ];
}
